QQmlValueTypeWrapper: fix build with -Walloca-larger-than=
It considers the possibility that the metatype returned size and
alignments of 0, thus causing space to be -1.

qqmlvaluetypewrapper.cpp:551:13: error: argument to ‘alloca’ is too large [-Werror=alloca-larger-than=]
qqmlvaluetypewrapper.cpp:551:13: note: limit is 9223372036854775807 bytes, but argument is 18446744073709551615

Amends 2ff1ff3a2ca4798f39d10e478e4a9e3c47811c4f.

Change-Id: I626bdff1c60376dfc418fffdd8e49d53e1b81c91
Reviewed-by: Ulf Hermann <ulf.hermann@qt.io>