VectorImage: add missing include
Amend f4dc2cf06bb816a0cf75e9b7e01bfdb6c3b1e16d and include for QSet to fix:

| src/quickvectorimage/generator/qquickqmlgenerator_p.h:159:19: error: field ‘m_generatedIds’ has incomplete type ‘QSet<QString>’
|   159 |     QSet<QString> m_generatedIds;
|       |                   ^~~~~~~~~~~~~~

Change-Id: I492ace0646810290fe144f5620741e248e22fe18
Reviewed-by: Eskil Abrahamsen Blomfeldt <eskil.abrahamsen-blomfeldt@qt.io>