Fix errors and warning if -no-feature-quick-viewtransitions is used
src/quick/items/qquickitemview.cpp:2657:22: error:
no member named 'transitionableItem' in 'FxViewItem'
 2657 |         delete item->transitionableItem;
      |                ~~~~  ^

src/quick/items/qquickitemview.cpp:2658:15: error:
no member named 'transitionableItem' in 'FxViewItem'
 2658 |         item->transitionableItem = nullptr;
      |         ~~~~  ^

src/quick/items/qquicklistview.cpp:3746:166: warning:
unused parameter 'movingIntoView' [-Wunused-parameter]
 3746 | bool [...]:applyInsertionChange([...] *movingIntoView)
      |                                        ^

Pick-to: 6.10 6.11
Change-Id: Ia37a0991ec5a75b0c52595daf88ccbcf94daa0aa
Reviewed-by: Mitch Curtis <mitch.curtis@qt.io>