QtQuickView statuslistener test: Use version-independent include
This amends e4971b51f8084ebb72dfea63a9b1930ea394b7c6
and should fix build failures like the Android one seen
for the Qt submodule update in [1]:

    agent:2025/06/13 05:11:49 build.go:412: /opt/android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=x86_64-none-linux-android28 --sysroot=/opt/android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMETA_LIB -DQT_QMLMODELS_LIB -DQT_QMLTEST_LIB -DQT_QMLWORKERSCRIPT_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DQT_TESTCASE_BUILDDIR=\"/home/qt/work/qt/qtdeclarative_standalone_tests/tests/auto/qtquickview/statuslistener/android-build/build/qt_generated/qml\" -DQT_TESTCASE_SOURCEDIR=\"/home/qt/work/qt/qtdeclarative_standalone_tests/tests/auto/qtquickview/statuslistener/android-build/qml\" -DQT_TESTLIB_LIB -Dtst_qtquickview_statuslistener_qml_EXPORTS -I/home/qt/work/qt/qtdeclarative_standalone_tests/tests/auto/qtquickview/statuslistener/android-build/build/qt_generated/qml/tst_qtquickview_statuslistener_qml_autogen/include -I/home/qt/work/qt/qtdeclarative_standalone_tests/tests/auto/qtquickview/statuslistener/android-build/qml -isystem /home/qt/work/install/target/include/QtQml -isystem /home/qt/work/install/target/include -isystem /home/qt/work/install/target/include/QtCore -isystem /home/qt/work/install/target/mkspecs/android-clang -isystem /home/qt/work/install/target/include/QtQmlIntegration -isystem /home/qt/work/install/target/include/QtNetwork -isystem /home/qt/work/install/target/include/QtQuick -isystem /home/qt/work/install/target/include/QtGui -isystem /home/qt/work/install/target/include/QtQmlMeta -isystem /home/qt/work/install/target/include/QtQmlModels -isystem /home/qt/work/install/target/include/QtQmlWorkerScript -isystem /home/qt/work/install/target/include/QtOpenGL -isystem /home/qt/work/install/target/include/QtQuickTest -isystem /home/qt/work/install/target/include/QtTest -isystem /home/qt/work/install/target/include/QtQuickTest/6.11.0 -isystem /home/qt/work/install/target/include/QtQuickTest/6.11.0/QtQuickTest -isystem /home/qt/work/install/target/include/QtTest/6.11.0 -isystem /home/qt/work/install/target/include/QtTest/6.11.0/QtTest -isystem /home/qt/work/install/target/include/QtCore/6.11.0 -isystem /home/qt/work/install/target/include/QtCore/6.11.0/QtCore -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O2 -g -DNDEBUG -std=gnu++17 -fPIC -fvisibility=default -Wall -Wextra -fPIC -pthread -MD -MT CMakeFiles/tst_qtquickview_statuslistener_qml.dir/tst_qtquickview.cpp.o -MF CMakeFiles/tst_qtquickview_statuslistener_qml.dir/tst_qtquickview.cpp.o.d -o CMakeFiles/tst_qtquickview_statuslistener_qml.dir/tst_qtquickview.cpp.o -c /home/qt/work/qt/qtdeclarative_standalone_tests/tests/auto/qtquickview/statuslistener/android-build/qml/tst_qtquickview.cpp
    agent:2025/06/13 05:11:49 build.go:412: /home/qt/work/qt/qtdeclarative_standalone_tests/tests/auto/qtquickview/statuslistener/android-build/qml/tst_qtquickview.cpp:4:10: fatal error: 'QtQuickTest/6.10.0/QtQuickTest/private/quickforandroidtest_p.h' file not found
    agent:2025/06/13 05:11:49 build.go:412: 4 | #include <QtQuickTest/6.10.0/QtQuickTest/private/quickforandroidtest_p.h>
    agent:2025/06/13 05:11:49 build.go:412: |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    agent:2025/06/13 05:11:49 build.go:412: 1 error generated.

[1] https://testresults.qt.io/logs/qt/qtdeclarative/975a91282e28a518a8a30b6425e5795c873a7d4a/LinuxRHEL_8_10x86_64AndroidAndroid_ANYx86_64GCCqtci-linux-RHEL-8.10-x86_64-51-8e0532AndroidTestRun_GenerateSBOM_Packaging_Sccache_UseConfigure_VerifySBOM_WarningsAreErrors/c72502c9a20723e5a9938f9d2caae2ee43c7809b/test_1749788448/log.txt.gz

Pick-to: 6.10
Task-number: QTBUG-133439
Change-Id: I58e0ce19e49b8f5ea286283e953392772cbd7a05
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>